= Disir - Text-based configuration files management

_Disir_ is a text-based configuration file management system. Why? Because configuration files are made to be configured. _They change_. When the provider of a configuration file changes the semantics of a configurable variable, this change is not propagated to deployed configuration files through an upgrade. Heck, even the changes made by the user is not saved through an update.

== But we have RPM, which readily stores modified configuration files as *.rpmnew. Why not just use that?

Because its **manual**. It does not aid you in resolving conflict between the saved backup and the new version. It provides no documentation **alongside** the configuration definition. It does not automatically provide type safety and restriction checks. This is all left up to be manually handled by the application deploying a configuration file. 

== Contributing Guidelines

* When first cloning the git repository, you must run the `dev/init_repo.sh` script
    to align your local git repository with upstream codebase policy.

* General codestyle guidelines include:
** Opening paranthesis to function calls and definitions shall be separated with a whitespace.
** Function return type skall be declared on a separate line above the function name.
** Line length shall strive to be under 100 characters long.
** Opening bracket shall be on a separate line.

== TODO List

[horizontal]
Restrictions:: No restritions are implemented on neither section nor keyval.

Update:: Allow update procedure to generate a collection of conflicts, instead of
resolving them immediately

Update:: Do not override the input config object, rather create a new one.

Update:: Iterate mold instead of config, to support add/removal/rename(?)

Update:: Create a detailed update report. Every keyval that changes value, either implicitly or
explicitly, should be part of the report. It should be split into entry sections, so they can be
merged into a single grand report detailing all changes. This should be implemented
after sections.

dc_context_compare()::  Implement a compare method. This should only every be true if
all children and state, even order-of-elements, are equal.
It might be reasonable to add a CRC or equivalent checksum that is computed for all contexts.
If so, this checksum MUST be take the order of operations into account.

verify:: Add some method to verify the state of the context. Should pinpoint an error message
to the invalid state characteristic.

value type:: Missing support for enums. These should be implemented as int64 and restrictions
should map their enum value to string representation.

Deprecrated:: Implement a deprecrated notion. KEYVALS and sections can be deprecrated

Rename:: KEYVALS and SECTION should possible be renamed across versions?

visiblity flag:: Annotate mold entries with a 'hidden' flag to indicate their presence,
but make them optional to a config entry - if queried and does not exist in the config,
it can be retrieved from the mold instead? This would allow us to hide ugly configuration
options that are so rarely changed, but still have them active in the configuration.

fixed flag:: Similar to visibilty flag, let the mold decide that this entry is of a fixed value
and wont show up on the configuration entry, but can be queried from it because
it will be retrieved in the mold instead.


== Developer dependencies

* cmake
* gtest
* gtest-devel
* (cmocka until it is deprecrated)
* doxygen
* gem install asciidoctor
* git@github.com:veeg/doxml2asciidoc
