= Disir - Text-based configuration files management

_Disir_ is a text-based configuration file management system. Why? Because configuration files are made to be configured. _They change_. When the provider of a configuration file changes the semantics of a configurable variable, this change is not propagated to deployed configuration files through an upgrade. Heck, even the changes made by the user is not saved through an update.

== But we have RPM, which readily stores modified configuration files as *.rpmnew. Why not just use that?

Because its **manual**. It does not aid you in resolving conflict between the saved backup and the new version. It provides no documentation **alongside** the configuration definition. It does not automatically provide type safety and restriction checks. This is all left up to be manually handled by the application deploying a configuration file. 

== Contributing Guidelines

* When first cloning the git repository, you must run the `dev/init_repo.sh` script
    to align your local git repository with upstream codebase policy.

* General codestyle guidelines include:
** Opening paranthesis to function calls and definitions shall be separated with a whitespace.
** Function return type skall be declared on a separate line above the function name.
** Line length shall strive to be under 100 characters long.
** Opening bracket shall be on a separate line.

== TODO List

[horizontal]
Restrictions:: No restritions are implemented on neither section nor keyval.


== Developer dependencies

* cmake
* gtest
* gtest-devel
* (cmocka until it is deprecrated)
* doxygen
* gem install asciidoctor
* git@github.com:veeg/doxml2asciidoc
