= Disir Core specification
Vegard Sandengen
Issue 0/1-draft

This document describes the Disir Core specification.
The specification itself is numbered with issue and revision.
Within each issue, there will be no breaking changes to the specification.
Each revision of an issue only contains clarifying additions or non-breaking
changes to the specification.

NOTE: This issue is *NOT* stable. Any changes done between revisions on
issue 0 may be breaking.

== Introducation

The Disir Core specification is intended to define a configuration entity, and its
formal description, resilient to upgrade operations when elements within the entity
changes properties across software versions.

This document describes the high-level functions to be performed to define
and construct a configuration entry and the properties one can express upon it,
in an implementation agnostic manner.

=== Motivation

The following properties are sought after when representing a configuration entity:

* Define key-value pairs of all nominal
data types (e.g., string, integer, float, boolean, and, enum).
* Group key-value pairs in different scopes, where each scope is identified by
a name.
* Provide documentation for each key-value pair and section.
* Verifying the value and relation between elements within configuration entry.
* Track changes of added and removed elements, changed default values for
a key-value pair across multiple versions of the configuration entity.
* Update the definition of the configuration entity, and perform an upgrade
operation on the existing values for changes applied to the definition in
the update process.
* Serialization agnostic method to representing the configuration entity.

Most existing implementations of representing key-value pairs provide
most of the four first bullets in the list above; however, they rarely address the
3 last points. They also often come bundled with the serialization format; making
comparison of existing solution tougher.

The primary motivation for this specification is to provide
a clever method to deploy configuration entities to the user that may naturally
evolve over time. This will aid the user in the sense that deprecated elements are
in fact removed from him, and the provider of the configuration entity does
not need to concern himself with legacy options; only those exposed in
the latest required version of the configuration entity is required.

=== Alternatives

There are no known alternatives to a serialization agnostic model to represent
key-value pairs and their relation. Which is quite understandable, since there is
little use of only a memory model for configuration; the whole point of it is to
retrieve the configuration from an external source.

Please see Disir Org specification for the full rundown how Disir Core is
used for organizing multiple configuration entities and serialization back-ends.

== Overview and definitions

A `configuration entry` is the highest order of abstraction in this specification.
It contains one or more `elements`:

* A `key-value` pair.
* A named `section` that contains elements (e.g., key-value pairs or sections, arbitrary nested).

A `mold entry` is required to express the configuration entry. It describes which elements are
present, their documentation, their default values and version history, and their restrictions.

A configuration entry is always versioned with regard to which version of the
mold entry it was last synced against.
If the configuration entry is missing this version sync marker, the default
version is assumed.
Each element in the mold entry is versioned. Changes to the properties of an element (e.g., the
default value, restrictions etc) warrant a version indication of the change from previous
version of the entire mold entry.

== Shared properties

This section contains shared properties used throughout this specification.

=== Version

A version number is used to track semantic changes of a definition throughout
a lifetime of updates. It is made up of two parts:

. Major version: non-negative integer. This number shall only be increased in the mold entry if
the changes within the mold are so severe that the semantic changes cannot be expressed
within the mold to automatically resolve the upgrade. Therefore, any configuration entry whose
major version does not match that of the mold entry shall be automatically rejected when
constructing the configuration entry object.
If this number is increased, the minor version number shall be reset to 0.
. Minor version: non-negative integer. This number increases whenever any changes to the mold
elements are performed that would alter the resulting configuration entry derived
from the mold entry.
This is currently limited to:
 * Default value changes
 * Additions and removal of elements
 * Changes to restrictions on elements.

The default version number when not present is "1.0".

=== Elements

A collection of elements that can be either a keyval or a section. The definition containing
an elements property is considered the parent scope for all elements in its collection.
Each element in the collection has a name property.

=== Restrictions

Disir allows to impair restrictions on elements within a mold.
They can be divided into two categorizes:

[horizontal]
inclusive:: All restrictions on the element must be fulfilled for the context to be valid.
exclusive:: Only one of the restrictions must be fulfilled for the element to be valid.

An element contains an array of restriction entries.
A restriction entry contains the following properties.

[horizontal]
Type:: The type of restriction. The following types are available:
* RESTRICTION_EXCLUSIVE_VALUE_ENUM: A valid value the keyval element may hold
  in the configuration entry.
* RESTRICTION_EXCLUSIVE_VALUE_RANGE: A valid range the value of the keyval element
  may be within in the configuration entry.
* RESTRICTION_EXCLUSIVE_VALUE_NUMERIC: A valid numeric value the keyval element
  may hold in the configuration entry.
* RESTRICTION_INCLUSIVE_ENTRY_MIN: The minimum number of elements of this kind must
  be present in the configuration entry for it to be valid. If not present,
  the default value employed is "0".
* RESTRICTION_INCLUSIVE_ENTRY_MAX: The maximum number of elements of this kind that
  may be present in the configuration entry for it to be valid. If not present,
  the default value employed is "1".
+
The restriction is invalid if no type is present.
If multiple restrictions of the same type is present on the same element, they cannot
have the same introduced version. If any are, they are considered invalid.
For the following types, a higher introduced restriction entry will supersede
a lower restriction entry even in the absence of a deprecated version on the lower entry:
RESTRICTION_INCLUSIVE_ENTRY_MIN, RESTRICTION_INCLUSIVE_ENTRY_MAX.
The definition of the restriction shall be able to set and retrieve this property.

Documentation:: A single, non-versioned string describing the purpose of this restriction.
This may only be applicable to a subset of types.
The definition of the restriction shall be able to set and retrieve this property.

Value:: The restriction definition holds a value depending on its type:
* RESTRICTION_EXCLUSIVE_VALUE_ENUM: Holds a string value.
* RESTRICTION_EXCLUSIVE_VALUE_MIN/RESTRICTION_EXCLUSIVE_VALUE_MAX: Hold a single integer
value.
* RESTRICTION_EXCLUSIVE_VALUE_NUMERIC: Hold a single integer or float value, depending on
the type of the keyval element.
* RESTRICTION_EXCLUSIVE_VALUE_RANGE: Holds two integer or float values, one of the upper and lower
bounds of the range definition. The restriction type depends on the type of the keyval element.
+
The definition of the restriction shall be able to set and retrieve this property.

Introduced:: See shared properties: Version.
This property denounces at which version number this restriction was first available in
the parent scope.
The definition of the restriction shall be able to set and retrieve this property.

Deprecated:: See shared properties: Version.
This property denounces at which version number this restriction is no longer available in
the parent scope.
The definition of the restriction shall be able to set and retrieve this property.

== Mold

This section describes an opaque object representing a mold entry and the properties
that defines it. A mold entry is valid if all its definitions and properties are valid.

=== Root

The top-level of a mold contains the following properties.

[horizontal]
Documentation:: A single, non-versioned string describing the purpose of this mold entry.
The definition of the mold root shall be able to set and retrieve this property.

Version:: See shared properties: Version.
A inferred version number for the mold, which equals the highest possible version
number observed in from all definitions within the mold.
This property is not settable in the definition of the mold root, only retrievable.

Elements:: See shared properties: Elements.
Multiple elements in the collection attempting to define
the same name in this scope will result in all successive definitions after the first to
becoming invalid.

=== Keyval

The mold keyval element contains the following properties.

[horizontal]
Name:: A single, non-versioned string that uniquely identifies the element in the parent scope.
The name is limited to the ASCII characters a-z, 0-9 and _. This is an artificial limitation
to enforce a consistent naming expression throughout and across multiple mold entries.
The definition of the element shall be able to set and retrieve this property.

Documentation:: A single, non-versioned string describing the purpose of this element
in its current scope. The definition of the element shall be able to set and retrieve this property.

Type:: Which type primitive this keyval represents. It may one of:
* Integer: signed 64 bit integer value.
* Float: floating point value.
* Boolean: a true/false value.
* String: variable length string that can hold an arbitrary unicode sequence.
* Enum: a set of predefined variable length strings, whose set are defined by a series of
RESTRICTION_EXCLUSIVE_VALUE_ENUM entries on the mold keyval.
+
This property can only be set for the version this keyval was introduced, and may not be changed
at any later version of the mold. However, this property shall be retrievable.

Restrictions:: See shared properties: Restrictions.
The following restrictions are applicable for the element:
* RESTRICTION_EXCLUSIVE_VALUE_ENUM
* RESTRICTION_EXCLUSIVE_VALUE_RANGE
* RESTRICTION_EXCLUSIVE_VALUE_NUMERIC
* RESTRICTION_INCLUSIVE_ENTRY_MIN
* RESTRICTION_INCLUSIVE_ENTRY_MAX

Introduced:: See shared properties: Version.
This property denounces at which version number this element was first available in
the parent scope. This property is not settable in the definition; rather, it is inferred
by the defaults array entries defined below. However, this property shall be retrievable.

Deprecated:: See shared properties: Version.
This property denounces at which version number this element is no longer available in
the parent scope. The definition of the element shall be able to set and retrieve this property.

Defaults:: An array of default definitions. The keyval is not valid without at least one
entry in the array. The following properties is part of a default definition:

* Introduced: See shared properties: Version. The version number when this default definition
is valid. If multiple definitions in the same defaults array contains the same version number,
all successive definitions after the first are considered invalid.
* A value container holding a value of the type defined in the mold keyval type property.

=== Section

The mold section element contains the following properties.

[horizontal]
Name:: A single, non-versioned string that uniquely identifies the element in the parent scope.
The name is limited to the ASCII characters a-z, 0-9 and _. This is an artificial limitation
to enforce a consistent naming expression throughout and across multiple mold entries.
The definition of the element shall be able to set and retrieve this property.

Documentation:: A single, non-versioned string describing the purpose of this element
in its current scope. The definition of the keyval shall be able to set and retrieve this property.

Introduced:: See shared properties: Version.
This priperty denounces at which version number this element was first available in
the parent scope. The definition of the element shall be able to set and retrieve this property.

Deprecated:: See shared properties: Version.
This property denounces at which version number this element is no longer available in
the parent scope. The definition of the element shall be able to set and retrieve this property.

Elements:: See shared properties: Elements.
Multiple elements in the collection attempting to define
the same name in this scope will result in all successive definitions after the first to
becoming invalid.

Restrictions:: See shared properties: Restrictions.
The following restrictions are applicable for the element:
. RESTRICTION_INCLUSIVE_ENTRY_MIN
. RESTRICTION_INCLUSIVE_ENTRY_MAX


== Config

This section describes an opaque object representing a config entry and the properties
that defines it. A config entry is valid if all its definitions and properties are valid.

=== Root

The top-level of a config contains the following properties.

[horizontal]
Version:: See shared properties: Version.
This version number represents at which point was the body of this config entry
synced with its corresponding mold entry.

Elements:: See shared properties: Elements.
The number of elements in this collection with the same name must conform to the inclusive
restrictions applied in its mold equivalent definition. Adding elements that violates these
inclusive restrictions does not turn that the root is invalid; rather, all
the afflicted elements are marked invalid instead.

=== Keyval

The config keyval element contains the following properties.

[horizontal]
Name:: A single, non-versioned string that equals one defined in equivalent scope
in the corresponding mold entry. If the name set is not found in equivalent scope,
the element is marked invalid. If the name is defined in the mold equivalent scope, but
for a version different than that defined by the config root, it shall be treated as non-existing.
The definition of the element shall be able to set and retrieve this property.

Value:: This propery cannot be set unless a valid name is such that a mold equivalent element
is located. The value set must be of the type specified in the mold equivalent element.
It must conform to the exclusive restrictions set by the mold equivalent.
The definition of the element shall be able to set and retrieve this property.

=== Section

The config section element contains the following properties.

[horizontal]
Name:: A single, non-versioned string that equals one defined in equivalent scope
in the corresponding mold entry. If the name set is not found in equivalent scope,
the element is marked invalid. If the name is defined in the mold equivalent scope, but
for a version different than that defined by the config root, it shall be treated as non-existing.
The definition of the element shall be able to set and retrieve this property.

Elements:: See shared properties: Elements.
The number of elements in this collection with the same name must conform to the inclusive
restrictions applied in its mold equivalent definition. Adding elements that violates these
inclusive restrictions does not turn that the root is invalid; rather, all
the afflicted elements are marked invalid instead.

