= Disir Org specification
Vegard Sandengen
Issue 0/1-draft

This document describe the Disir Org specification.
The specification itself is numbered with issue and revision.
Within each issue, there will be no breaking changes to the specification.
Each revision of an issue only contains clarifying additions or non-breaking
changes to the specification.

NOTE: This issue is *NOT* stable. Any changes done between revisions on
issue 0 may be breaking.

== Introduction

The Disir Org specification is intended to define a complete ecosystem
to manage a set of config entries as defined by the Disir Core
specification. This specification allows multiple conforming implementations
to export and import their config entries when the same
serialization format is used on both ends.

Disir Org does not mandate the format of the serialized/unserialized entries, this
is implementation specific. However, it requires the implementation to
implement a set of equivalent API end-points that interacts with the system.

=== Motivation

The following properties are sough after from this ecosystem:

* Allow entries to be grouped, uniquely identified by a string key.
* Define a naming scheme to identify all entries in a group.
* Allow multiple config entries to be represented by a single mold entry.
* Perform group-wide update operation with full reporting of changes applied after
the system upgraded their mold entries.
* Import/export config entries from the system.
This includes the complete set, as well as a subset of entries selected at export time.

The separation of mold and config entry allows the Disir Org to derive the config
from the mold in the absence of the config entry. Clearing all config entries
will effectively perform a system reset.
Therefore, there is no reason to persist the config entry
in the back-end unless the user explicitly wants to perform changes to the derived default.

A key component of this specification is the ability for the mold provider to define
a namespace mold entry, for which the user can easily create multiple, differently named,
config entries from it. This allows the system provider to install pre-defined entries,
and allows the user to add additional entries. With the native import/export functionality,
this easily allows the user to sync config between similar/equal systems. However,
this sync functionality is not part of this specification. We only regard a single system
in this specification.

A rule of thumb from this specification is that the user owns all config entries;
the system shall not provide nor interfere with the config entries unless explicit
action is requested from the user
(e.g., modify operations through an editor or import/export requests).

=== Alternatives

`dconf` is a GNOME project to provide a back-end for GSettings for platforms
that otherwise does not provide a configuration storage system.
It is a very simple back-end that is optimized for reading keys,
which is quite frankly also the most common use case.
It provides no validation (which is rather provided by GSettings)
and no out-of-the-box import/export entries.
Neither does it allow the user to add arbitrary entries defined by the same schema.

`GSettings` is the programmers interface to reading configuration on a GNOME system.
Each entry is provided by the programmer as a schema defining mount path (within GSettings,
the tree of different entries to navigate), acceptable keys and their restrictions.
In this regard, it provides everything (as far as is known) also provided by the mold entry.
However, it lacks the support to properly modify the schema across versions of the entry.
This excludes using GSettings, even if we provided our own back-end instead of dconf.

== Overview and definitions

This section describes various core concepts of the Disir Org specification.

The core idea behind Disir Org is to have an organized way of interacting
with system defined mold entries, and have the system entirely own the mold entries.
The config entries is the property of the user. We must allow the user to provide
his own config entries. To this extent, we also must provide a mechanism for
the user to export and import config entries to and from the system.
The method for the system to provide mold entries is an implementation detail.


=== Naming

The Disir Org specification provides an ecosystem for the primitives defined in the Disir Core
specification. Our main objective is to interact with a set of entries,
therefore, we need to identify them.
We assign each a unique entry an `entry_id`,
often specified when necessary as config entry id or mold entry id. This is
a string that may only contain the ASCII characters a-z, 0-9 and _ and /.
Therefore, the mold entry id `employee/bob` is the mold definition for the config entry id
`employee/bob`.

=== Namespace

The Disir Core specification mandates that a config entry must be represented by a mold entry;
however, it does not require the config to be one-to-one mapped. That is; we can use a single
mold entry to represent multiple config entries. We leverage this to define a `namespace entry`.
The mold entry id for a namespace entry must end in a forward-slash (/).
Therefore, `employee/` is a mold entry id that is a namespace entry.
All config entry id's that does not have a
non-namespace mold entry id with a matching prefix to the mold entry id and
contains no additional forward-slashes is considered a namespace entry.
That would make `employee/alice` a namespace config entry id, but not
`employee/meta/leadership` due to the presence of a forward-slash after the matching prefix (
unless `employee/meta/` is also a namespace mold entry id). Expanding on the example above,
given that `employee/bob` is a mold entry id, the config entry id `employee/bob` does not
derive its definition from the namespace mold entry id `employee/`.

=== Groups

To cleanly separate different instances of the hierarchy of entry ids,
each interaction with Disir Org must specify a string `group_id` alongside the entry id.
This means that the entry id `employee/dan` is two distinct entries if accessed with different
group id.

=== Serialization

Disir Core does not define a serialization method; its a pure abstract model.
Disir Org does neither enforce any serialize/deserialize format nor model for how
to implement support single/various back-ends. However, in order to support
an export archive of config entries, we require a method of identifying
a particular serialize/deserialize back-end used when interacting with the tuple
(group_id, entry_id). We call this back-end identifier for `serialization_id`
This allows us to export config entries to an archive with the tuple (serialization_id,
group_id, entry_id), move this archive around and import the entries in the archive
given that the implementation at the import location
supports the deserialize back-end given by the serialization_id.


== API

The expected operations that must be supported by a conforming implementation
are detailed in this section. These endpoints are merely described in a fashion
to give insight into the expected behaviour from Disir Org - their implementation
and convenience/extensions are not mandated.

=== CONFIG_READ

Provided with the parameters group_id and entry_id, the operation shall
return an opaque object that may be queried, modified and written back.

=== CONFIG_WRITE

Provided with the parameter group_id, entry_id and config_object,
the operation shall on success persist the config_object to storage
that shall is not of a temporary nature.

=== MOLD_READ

Provided with the parameters group_id and entry_id, the operation shall
return an opaque object that may be queried.

=== EXPORT

Provided with the parameters serialization_id, group_id, entry_id and
archive_filepath, the operation shall serialize the tuple (serialization_id,
group_id, entry_id) to the archive pointed to by the filesystem path archive_filepath.
If no archive exists at the file system path archive_filepath, the archive shall be created.

=== IMPORT

Provided with the parameters serialization_id, group_id, entry_id and archive_filepath,
the operation shall unserialize the config entry from the archive and write it
to system. If no mold entry exists for the tuple (group_id, entry_id) on the system,
the operation shall fail.

== Archive

An exported bundle of config entries are serialized to a compressed file archive.
This section details the format of this archive and the intention behind
the various components.

For a conforming Disir Org implementation to support archive, it will require
to implement a serialize/deserialize interface for config entries to a blob byte
storage. Attached to this interface there must exist a serialization_id, a
UTF-8 encoded string identifier of at most 512 bytes, to identify the mechanism
used when serializing, and subsequently use the same mechanism to deserialize
the content.

=== File format

The export file is a tar archive compressed with `xz`. The file extension does _not_
reflect this, but rather simply contains the extension `.disir`.

The archive contains a single folder, which is named equal to the export file name, without
the archive extension.

In the archive, there is a single file, `metadata.toml`, which is the solely determines the
content of the archive. The file is formatted using the TOML file format.
The following TOML key-value pairs are defined for this file:

[horizontal]
disir_org_version:: String identifier for which version of the Disir Org specification
this archive was constructed after. Example: "0/1-draft".
When importing, the Disir Org implementation MUST reject interacting with
an archive where this string identifier is not in the set of supported
specifications.

implementation:: String identifier of the implementation and version that produced
this archive. Example: "disir_c/0.1.0". This identifier is purely informational
and has no significant meaning in nominal situations.

backend:: Array of tables entry, where each entry enumerates a serialization_id who
exported entries for one or more groups. The following keys are defined for each back-end:

. *serialization_id*: String identifier that the plugin exported.
  This identifier must match on the export and import system so
  that the same back-end may process the contents.
. *groups*: Array of strings, one for each group_id exported in the
  archive for this serialization_id.

Any keys-value pairs found that does not match those listed here shall be
ignored for future-compatibility.

.Example: metadata.toml
[source, toml]
----
disir_org_version = "0/1-draft"
implementation = "disir_c/0.1.0"

[[backend]]
  serialization_id = "JSON"
  groups = ["meos", "kspt"]
----

For each back-end present in the metadata, the archive expects a folder in the root directory
named identical to the serialization_id.
Within this directory, the archive expects to find a single file
named `entries.toml`. This file is formatted using the TOML file format.

The expected key-value pairs for this file is a table for each
group found in the respective groups array in the `metadata.toml` file under the
sub-table matching serialization_id and the current working directory of this `entries.toml`.
For each table, the keys are quoted for each entry_id, where the value
is a string representation of their version.

Any keys-value pairs found that does not match those listed here shall be
ignored for future-compatibility.


.Example: JSON/entries.toml
[source, toml]
----
[meos]
  "system/preferences" = "1.0"
  "mission/link/aqua" = "1.5"

[kspt]
  "user/boot" = "1.0"
  "user/preferences" = "1.1"
----

Each group has a dedicated folder in the serialization_id folder, where all their
config entries are serialized by their entry_id following their hierarchical naming scheme.

.Example: Tree structure for the above metadata and entries
----
metadata.toml
JSON/kspt/user/boot
JSON/kspt/user/preferences
JSON/meos/mission/link
JSON/meos/mission/link/aqua
JSON/meos/system/preferences
JSON/entries.toml
----

