#ifndef _LIBDISIR_LIBDISIR_H
#define _LIBDISIR_LIBDISIR_H

#ifdef __cplusplus
extern "C"{
#endif // __cplusplus

#include <disir/disir.h>

//! \brief Create a mold for the libdisir configuration entry.
//!
//! This function is exposed to the public API such that appropriate documentation
//! may be generated by external tools, instead of relying on the mold definition
//! which is programmatically embedded in libdisir.
//!
//! \param[out] mold Populated address with the created mold.
//!
//! \return DISIR_STATUS_OK on success.
//!
DISIR_EXPORT
enum disir_status
disir_libdisir_mold (struct disir_mold **mold);

//! \brief Output the libdisir config entry to disk.
//!
//! \param[in] instance Disir library instance associated with this operation.
//! \param[in] config Valid configuration object based of libdisir_mold
//! \param[in] filepath Path to disk location to write the INI-formatted config file.
//!
//! \return DISIR_STATUS_OK on success.
//!
DISIR_EXPORT
enum disir_status
disir_libdisir_config_to_disk (struct disir_instance *instance,
                               struct disir_config *config,
                               const char *filepath);

//! \brief Read the libdisir_config entry from disk.
//!
//! \param[in] instance Disir library instance associated with this operation.
//! \param[in] filepath Full filepath to the location on disk to locate the configuration file.
//! \param[in] mold Mold instance for libdisir.
//! \param[out] config The config structure to populate with the read configuration file.
//
//! \return DISIR_STATUS_INVALID_ARGUMENT if config_filepath cannot be opened.
//! \return DISIR_STATUS_OK on success.
//!
DISIR_EXPORT
enum disir_status
disir_libdisir_config_from_disk (struct disir_instance *instance,
                                 const char *filepath,
                                 struct disir_mold *mold,
                                 struct disir_config **config);


#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _LIBDISIR_LIBDISIR_H

