= *Disir* Developer Documentation

This document details the nitty gritty details of how Disir is designed and
rationale behind various implementation details.

[horizontal]
.Dictionary
Element container:: Either context SECTION, CONFIG or MOLD.
Element:: Either context SECTION or KEYVAL.

== Context validity

A context may have one of two states: constructing or finalized. When a context is constructing,
Disir will still process any operation that places the context in an invalid state, and the
status code DISIR_STATUS_INVALID_CONTEXT is returned. This status shall only ever be returned
from context functions when the context is in constructing state.

The rationale for handling the complexity of storing objects with invalid state is to allow
unserialization to completely construct the object, regardless of how invalid it is.
After the unserialization is complete, and the object is finalized, the erroneous conditions
can be programmatically retrieved and displayed to a human user who may take corrective measures.
It is far more user friendly to be prompted with fully parsed view of the object, with
only those that are invalid marked with an appropriate error message, than throwing 'an error has
ocurred in parsing. Please fix' at the user.

Finalized state means that any operation that places the context in an invalid state, shall be
denied with an appropriate status, e.g., DISIR_STATUS_RESTRICTION_VIOLATED.

There are quite a few cases that may lead objects into invalid state.

* Element containers may be invalid if an element in its mold does not
fulfill maximum or minimum requirements.
* Element may be invalid because its name is not found in the mold.
* Element may be invalid because its value type is not equal to that of the mold.
* Element may be invalid because its value does not satisfy one of the exclusive restrictions
put in place by the mold.
* Finalizing invalid context to a finalized parent shall be dis-allowed. Do not
enter the context into the element storage of the parent(element container).

From the above rules, we may conclude that CONFIG context shall not be in invalid state
if one of their elements are invalid, unless that invalidity is due to maximum or minimum requirements.

Internal functions shall _NOT_ return DISIR_STATUS_INVALID_CONTEXT, that is solely the
responsibility of the outer public API methods to convert based on context state. (This is
with the exception of dx_validate_context, which hides all the rough details of validating
our contexts)

QUESTION: Shall the element within an element container be invalid if it does not fulfill
the maximum/minimum requirements of its element container?

== Notes

*What are there calls to `dx_crash_and_burn` in library code that exits the program*?
Simple answer is there shouldnt be, but they are put in place during initial development
to crash early and crash hard. When the library is stabilized, all these calls will be replaced
with a proper return statement.
