= End User Documentation

A text-configuration file is represented by a schema that describes it, its values
and more importantly, its state. There is a one-to-one mapping between a configuration
file and a schema representing it.

When a package installs a _Disir_ configuration file, it is really installing a schema to the system.
So, without further intervention, the configuration file is not actually present on the system.
This allows the package to update the schema, with proper semantic versioning of the updated fields,
without overwriting the already present configuration file on the system. Thus, when the package is
updated, either the package post install process or the end-user may attempt to update the installed
configuration to the new state of the updated schema. 

If non of the updated fields in the schema are changed in the installed configuration,
there are no conflicts and we may happily update that installed configuration.
If a conflict occurs, it may require human intervention
to properly update the configuration with the appropriate values.

The process of generating/updating a configuration file may be done either programmatically,
through a command line utility or graphically.

== Disir Group

The configuration file may reside anywhere on disk, which is in reallity backed up by a schema
categorized into a *Disir Group*.

The _Disir Group_ is a way to organize loosely related configuration files together.
Each _Disir Schema_ must be categorized under a group. 

There exists two groups with special meaning:

[horizontal]
**default**:: The group which all non-specified schemas are located.

**all**:: Will include all groups into the operation when interacting with _Disir_.

The schemas are therefore installed into a group folder under `/etc/disir/groups`, with
the full path of its location on disk.

.Example: Given the configuration file:
----
/etc/progit/flash.xml
----

The corresponding _Disir Schema_, categorized into the default group, would be located at

----
/etc/disir/groups/default/etc/progit/flash.xml
----

When running a `disir update /etc/progit/flash.xml`, the corresponding schema file is located and
parsed first. Then the semantic version number of the schema file is compared with that of the 
configuration file. If they are equal, no update is required. If they differ, _Disir_ will attempt
to merge the updated fields in the schema into the configuration. Conflict resolution is
performed based on the strategy the update command was invoked with. 


== Disir Config

Two key attributes within the _Disir Config_ associates it with _Disir_. 

[horizontal]
**Disir_version**:: The configuration file can identify the deployed version of itself.
If this attribute is not present, _Disir_ will assume the default semantic version number 1.0.0.

**Disir_group**:: The configuration file is associated with this named group.
If no attribute is provided or it is empty, the **default** group is assigned.

